In [1]:
#Dependencies
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from citipy import citipy
import requests
from config import weather_api_key
import time
from datetime import datetime

In [2]:
#2000 random locations
lats = np.random.uniform(-90, 90, size=2000)
lngs = np.random.uniform(-180, 180, size=2000)
lat_lngs = zip(lats, lngs)

In [3]:
#Add lat_lngs to a list
coordinates = list(lat_lngs)

In [4]:
#Create a list
cities = []
#Identidfy nearest cities
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name
    
    #If city is unique then add to the list
    if city not in cities:
        cities.append(city)
#Print city count
len(cities)

758

In [5]:
#Create Url
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key

In [6]:
#Create an empty list to hold the weather data
city_data = []
#Loop through list of cities
for i, city in enumerate(cities):
    # Create endpoint URL with each city.
    city_url = url + "&q=" + city.replace(" ","+")
    #Run an API request for each city
    try:
        # Parse the JSON and retrieve data
        city_weather = requests.get(city_url).json()
        # Parse out the needed data
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        current_description = city_weather["weather"][0]["description"]
        # Convert the date to ISO standard
        city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S')
        # Append the city information into city_data list
        city_data.append({"City": city.title(),
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Max Temp": max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country,
                          "Date": city_date,
                          "Current Description": current_description})

    # If an error is experienced, skip the city
    except:
        print("City not found. Skipping...")
        pass

City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...

In [7]:
len(city_data)

695

In [8]:
weather_df = pd.DataFrame(city_data)
weather_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description
0,Bluff,-46.6000,168.3333,59.81,96,60,6.49,NZ,2022-02-01 12:57:24,broken clouds
1,Nouadhibou,20.9310,-17.0347,71.58,64,98,8.05,MR,2022-02-01 12:57:24,haze
2,Jamestown,42.0970,-79.2353,22.71,46,100,5.99,US,2022-02-01 12:57:25,overcast clouds
3,Rawson,-43.3002,-65.1023,70.95,44,6,16.46,AR,2022-02-01 12:57:25,clear sky
4,Morant Bay,17.8815,-76.4093,74.82,80,27,9.40,JM,2022-02-01 12:57:25,scattered clouds

In [9]:
new_order = ["City", "Country", "Lat", "Lng", "Max Temp", "Humidity", "Cloudiness", "Wind Speed", "Current Description"]

In [10]:
weather_df = weather_df[new_order]
weather_df

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,Bluff,NZ,-46.6000,168.3333,59.81,96,60,6.49,broken clouds
1,Nouadhibou,MR,20.9310,-17.0347,71.58,64,98,8.05,haze
2,Jamestown,US,42.0970,-79.2353,22.71,46,100,5.99,overcast clouds
3,Rawson,AR,-43.3002,-65.1023,70.95,44,6,16.46,clear sky
4,Morant Bay,JM,17.8815,-76.4093,74.82,80,27,9.40,scattered clouds
...,...,...,...,...,...,...,...,...,...
690,La Rioja,ES,42.2500,-2.5000,49.32,91,100,6.22,overcast clouds
691,Havelock,US,34.8791,-76.9013,39.15,91,17,7.96,few clouds
692,Skibbereen,IE,51.5500,-9.2667,53.40,82,25,18.16,scattered clouds
693,Azad Shahr,IR,34.7909,48.5707,35.17,73,76,7.43,broken clouds
694,Alice Town,BS,25.7167,-79.3000,68.54,56,48,18.23,scattered clouds

In [11]:
#create print file
print_file = "WeatherPy_Database.csv"
#Print
weather_df.to_csv(print_file)

In [ ]:
#The End